project:
  type: website
  output-dir: docs
  resources: 
    - Isaac_Vock_CV.pdf

website:
  title: "isaacvock.github.io"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Research
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

