project:
  type: website
  resources: 
    - Isaac_Vock_CV.pdf

website:
  title: "isaacvock.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

